debian-bluster-slim;jdk8u232;maven3.6.2

diff --git a/8-slim/Dockerfile b/8-slim/Dockerfile
--- a/8-slim/Dockerfile
+++ b/8-slim/Dockerfile
@@ -4,55 +4,62 @@
 # nano
 # maven
 
-FROM debian:stretch-slim
+FROM debian:buster-slim
 
 MAINTAINER zooltech (zooltech@qq.com)
 
 # Default to UTF-8 file.encoding
 ENV LANG C.UTF-8
-ENV JAVA_HOME /docker-java-home
-ENV JAVA_VERSION 8u181
-ENV JAVA_DEBIAN_VERSION 8u181-b13-2~deb9u1
+ENV JAVA_HOME /usr/share/java
+ENV PATH $JAVA_HOME/bin:$PATH
 
-# see https://bugs.debian.org/775775
-# and https://github.com/docker-library/java/issues/19#issuecomment-70546872
-ENV CA_CERTIFICATES_JAVA_VERSION 20170531+nmu1
+# java install params
+ARG JAVA_URL_VERSION=8u232b09
+ARG JAVA_BASE_URL=https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u232-b09/OpenJDK8U-jdk_
 
-RUN set -ex; \
-# deal with slim variants not having man page directories (which causes "update-alternatives" to fail)
-	if [ ! -d /usr/share/man/man1 ]; then \
-		mkdir -p /usr/share/man/man1; \
-	fi; \
-	apt-get update \
-	&& apt-get install -y --no-install-recommends bzip2 unzip xz-utils wget git nano openjdk-8-jdk-headless="$JAVA_DEBIAN_VERSION" ca-certificates-java="$CA_CERTIFICATES_JAVA_VERSION"; \
-	rm -rf /var/lib/apt/lists/*; \
-# add a simple script that can auto-detect the appropriate JAVA_HOME value
-# based on whether the JDK or only the JRE is installed
+# maven install params
+ARG MAVEN_VERSION=3.6.2
+ARG MAVEN_BIN_URL=http://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
+
+RUN set -eux; \
+	dpkgArch="$(dpkg --print-architecture)"; \
+	case "$dpkgArch" in \
+		amd64) upstreamArch='x64' ;; \
+		arm64) upstreamArch='aarch64' ;; \
+		*) echo >&2 "error: unsupported architecture: $dpkgArch" ;; \
+	esac; \
+	apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends nano wget git ca-certificates p11-kit && rm -rf /var/lib/apt/lists/*; \
+	wget -O openjdk.tgz "${JAVA_BASE_URL}${upstreamArch}_linux_${JAVA_URL_VERSION}.tar.gz" --progress=dot:giga; \
+	mkdir -p "$JAVA_HOME"; \
+	tar --extract --file openjdk.tgz --directory "$JAVA_HOME" --strip-components 1 --no-same-owner; \
+	rm openjdk.tgz*; \
+	rm "$JAVA_HOME/src.zip" && rm -rf "$JAVA_HOME/demo" && rm -rf "$JAVA_HOME/sample"; \
+# update "cacerts" bundle to use Debian's CA certificates (and make sure it stays up-to-date with changes to Debian's store)
+# see https://github.com/docker-library/openjdk/issues/327
+#     http://rabexc.org/posts/certificates-not-working-java#comment-4099504075
+#     https://salsa.debian.org/java-team/ca-certificates-java/blob/3e51a84e9104823319abeb31f880580e46f45a98/debian/jks-keystore.hook.in
+#     https://git.alpinelinux.org/aports/tree/community/java-cacerts/APKBUILD?id=761af65f38b4570093461e6546dcf6b179d2b624#n29
+	mkdir -p /etc/ca-certificates/update.d; \
 	{ \
-		echo '#!/bin/sh'; \
-		echo 'set -e'; \
-		echo; \
-		echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
-	} > /usr/local/bin/docker-java-home \
-	&& chmod +x /usr/local/bin/docker-java-home; \
-	ln -svT "/usr/lib/jvm/java-8-openjdk-$(dpkg --print-architecture)" /docker-java-home; \
-# verify that "docker-java-home" returns what we expect
-	[ "$(readlink -f "$JAVA_HOME")" = "$(docker-java-home)" ]; \
-# update-alternatives so that future installs of other OpenJDK versions don't change /usr/bin/java
-	update-alternatives --get-selections | awk -v home="$(readlink -f "$JAVA_HOME")" 'index($3, home) == 1 { $2 = "manual"; print | "update-alternatives --set-selections" }'; \
-# ... and verify that it actually worked for one of the alternatives we care about
-	update-alternatives --query java | grep -q 'Status: manual'
-
-ARG MAVEN_VERSION=3.6.0
-ARG MAVEN_BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries
-
-# see CA_CERTIFICATES_JAVA_VERSION notes above
-RUN echo "alias ls='ls --color=auto'\nalias ll='ls -lA'" > /root/.bashrc; \
-  /var/lib/dpkg/info/ca-certificates-java.postinst configure; \
-  wget ${MAVEN_BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz -P /tmp \
-  && mkdir -p /usr/share/maven \
-  && tar zxf /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /usr/share/maven --strip-components=1\
-  && rm -f /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
-  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
+		echo '#!/usr/bin/env bash'; \
+		echo 'set -Eeuo pipefail'; \
+		echo 'if ! [ -d "$JAVA_HOME" ]; then echo >&2 "error: missing JAVA_HOME environment variable"; exit 1; fi'; \
+# 8-jdk uses "$JAVA_HOME/jre/lib/security/cacerts" and 8-jre and 11+ uses "$JAVA_HOME/lib/security/cacerts" directly (no "jre" directory)
+		echo 'cacertsFile=; for f in "$JAVA_HOME/lib/security/cacerts" "$JAVA_HOME/jre/lib/security/cacerts"; do if [ -e "$f" ]; then cacertsFile="$f"; break; fi; done'; \
+		echo 'if [ -z "$cacertsFile" ] || ! [ -f "$cacertsFile" ]; then echo >&2 "error: failed to find cacerts file in $JAVA_HOME"; exit 1; fi'; \
+		echo 'trust extract --overwrite --format=java-cacerts --filter=ca-anchors --purpose=server-auth "$cacertsFile"'; \
+	} > /etc/ca-certificates/update.d/docker-openjdk; \
+	chmod +x /etc/ca-certificates/update.d/docker-openjdk; \
+	/etc/ca-certificates/update.d/docker-openjdk; \
+# https://github.com/docker-library/openjdk/issues/331#issuecomment-498834472
+	find "$JAVA_HOME/lib" -name '*.so' -exec dirname '{}' ';' | sort -u > /etc/ld.so.conf.d/docker-openjdk.conf; \
+	ldconfig; \
+# download and install maven
+	wget ${MAVEN_BIN_URL} --progress=dot:giga; \
+	mkdir -p /usr/share/maven \
+	&& tar zxf apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /usr/share/maven --strip-components=1 \
+	&& rm -f apache-maven-${MAVEN_VERSION}-bin.tar.gz \
+	&& ln -s /usr/share/maven/bin/mvn /usr/bin/mvn;\
+	echo "alias ls='ls --color=auto'\nalias ll='ls -lA'" > /root/.bashrc
 
 ENV MAVEN_HOME /usr/share/maven
